### PR TITLE
Added kanux_stamp file to the list

### PR DESCRIPTION
**Pull request by radujipa**
Related to: https://github.com/KanoComputing/kano-feedback/pull/85

### CODE REVIEW

**Comment by radujipa** [comment]
[(1) As an engineer, I want to change the error messages for V30DB so I can learn more about what's going on [2]](https://trello.com/c/fVSfXXqG/1747-1-as-an-engineer-i-want-to-change-the-error-messages-for-v30db-so-i-can-learn-more-about-whats-going-on-2)

**Comment by alex5imon** [comment]
Kanux :_)

**Comment by radujipa** [comment]
THE CAPTAIN! 👍

**Comment by alex5imon** [comment]
Please merge :)

**Comment by skarbat** [comment]
@alex5imon !!!   :-D

**Pull request merged**
